# Generated by Django 6.0.2 on 2026-02-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_token_jti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
