# Generated by Django 6.0.2 on 2026-02-17 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_user_current_token_jti'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('SPECIAL', 'Special'), ('MEETING', 'Meeting Request')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('LAB', 'Lab'), ('CLASSROOM', 'Classroom'), ('EVENT_HALL', 'Event Hall'), ('MEETING_ROOM', 'Meeting Room / Office'), ('COMPUTER', 'Computer')], max_length=20),
        ),
        migrations.CreateModel(
            name='MeetingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myproject.resource')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='scheduled_meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
